version: 1.1.0.{build}
before_build:
- dir
- dir C:\
- dir C:\Libraries
- dir "C:\Program Files (x86)"
- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe" temptemp.cpp


build_script:
- echo %var1%
- echo %var2%
