version: 1.1.0.{build}
before_build:
- dir
- dir C:\
- dir C:\Libraries
- dir C:\Libraries\boost1_58_0
- dir C:\Libraries\boost
- dir C:\Libraries\boost\stage\lib
- dir "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin"

environment:
  matrix:
    - var1: A
      var2: C
    - var1: B
      var2: D

build_script:
- echo %var1%
- echo %var2%
