version: 1.1.0.{build}
before_build:
- dir
- dir C:\
- dir C:\Libraries
- dir C:\Libraries\boost
- dir C:\Libraries\boost\stage\lib

environment:
  matrix:
    - var1: A
      var2: C
    - var1: B
      var2: D

build_script:
- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe" template_specialize.cpp
- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe" temptemp.cpp
- echo %var1%
- echo %var2%
