version: 1.1.0.{build}
os: Previous Visual Studio 2015

before_build:
- dir
- dir C:\
- dir C:\Libraries
- dir "C:\Program Files (x86)"


build_script:
- call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe"
- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\CL.exe" temptemp.cpp
- echo %var1%
- echo %var2%
