version: 1.1.0.{build}
before_build:
- dir
- dir C:\
- dir C:\Libraries
- dir C:\Program Files (x86)
- dir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0'
- dir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC'
- dir 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin'


build_script:
- echo %var1%
- echo %var2%
