version: 1.1.0.{build}
before_build:
- dir
- dir C:\
- dir C:\Libraries
- dir C:\Libraries\boost
- dir C:\Libraries\boost\stage\lib

environment:
var1: A
var2: B

build_script:
- echo var1
- echo %var1%
- echo var2
- echo %var2%
